<link rel="stylesheet" href="{{ asset('assets/css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/bootstrap-responsive.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/font-awesome.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/select2.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/bootstrap-multiselect.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/prettify.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/buttons.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/app.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/forms.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/auth.css') }}">
